name: Poker Server CD

on:
  push:
    branches: [release]
    paths:
      - "src/**"
      - "build.sbt"
      - "project/**"
      - ".github/workflows/poker-cd.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: read 

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.POKER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.POKER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.POKER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: docker.io
          registryUsername: ${{ secrets.POKER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.POKER_REGISTRY_PASSWORD }}
          containerAppName: scalapoker
          resourceGroup: poker-rg
          imageToBuild: ${{ secrets.POKER_REGISTRY_USERNAME }}/scalapoker:${{ github.sha }}